services:
  db:
    image: postgres:latest
    container_name: weather_db
    restart: always
    env_file: .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '${POSTGRES_PORT}:5432'

volumes:
  pgdata: {}
